cafe/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace cafe.Models
{
    public class Customer
    {
        //will increment the customer by Id
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set;  }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string PostCode { get; set; }
        public string Telephone { get; set; }
        public int Age { get; set; }
    }
}

cafe/Models/CustomerContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace cafe.Models
{
    public class CustomerContext: DbContext
    {

        public CustomerContext(DbContextOptions options) : base(options)
        {
        }


        public DbSet<Customer> Customers { get; set; }
    }
}

cafe/Models/ErrorViewModel.cs
using System;

namespace cafe.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cafe/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using cafe.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace cafe.Controllers
{
    public class CustomerController : Controller
    {
        // DbContext Config
        private readonly CustomerContext _context;

        public CustomerController(CustomerContext context)
        {
            _context = context;
        }

        //TODO : Work more on the validation of user's input in particualr for postCode and telephone 
        //TODO : Improve the style of the Views by adding bootstarp elements
        //TODO : Add page number and set the max of the items of every set of view to 20 customers.
        //TODO: Add Loading bootstrap when users list is loading
        //TODO : Add ErrorHandler to deal with different cases when user enter invalid values
        // or there is a an internal server error
        //TODO: Create DependancyInject to facilitate the work in future if we need to edit particualr objects
       

        // Customers List
        public IActionResult Index()
        {
            List<Customer> customers = _context.Customers.ToList();
            return View(customers);
        }


        // Customer Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _context.Customers.Find(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

       

        // [HttpGET]
        // Add or Update Customer based on Id
        public async Task<IActionResult> AddOrEdit(int? Id)
        {
            ViewBag.PageName = Id == null ? "Create Customer" : "Edit Customer";
            ViewBag.IsEdit = Id == null ? false : true;
            if (Id == null)
            {
                return View();
            }
            else
            {
                var customer = await _context.Customers.FindAsync(Id);

                if (customer == null)
                {
                    return NotFound();
                }
                return View(customer);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int Id, [Bind("Id,Title,FirstName,SureName,Address1,Address2,Address3,Address4,Telephone,PostCode,Age")]
Customer customerData)
        {
            bool IsCustomerExist = false;

            Customer customer = await _context.Customers.FindAsync(Id);

            if (customer != null)
            {
                IsCustomerExist = true;
            }
            else
            {
                customer = new Customer();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    customer.Title = customerData.Title;
                    customer.FirstName = customerData.FirstName;
                    customer.Surname = customerData.Surname;
                    customer.Address1 = customerData.Address1;
                    customer.Address2 = customerData.Address2;
                    customer.Address3 = customerData.Address3;
                    customer.Address4 = customerData.Address4;
                    customer.Telephone = customerData.Telephone;
                    customer.PostCode = customerData.PostCode;
                    customer.Age = customerData.Age;

                    if (IsCustomerExist)
                    {
                        _context.Update(customer);
                    }
                    else
                    {
                        _context.Add(customer);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customerData);
        }

        
        // GET: Customer/Delete/1
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var customer = await _context.Customers.FirstOrDefaultAsync(m => m.Id == Id);

            return View(customer);
        }

        // POST: Customer/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int Id)
        {
            var customer = await _context.Customers.FindAsync(Id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


    }
}

cafe/Views/Customer/AddOrEdit.cshtml
@model cafe.Models.Customer

@{
    ViewData["Title"] = "Create";
}



<div class="container p-3 my-3 border">
    <h1> @ViewBag.PageName</h1>

    <div class="row">
        <div class="col-sm-6">
            <hr />
            <form asp-action="AddOrEdit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @if (@ViewBag.IsEdit)
                {
                    <input type="hidden" asp-for="Id" />
                }
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Surname" class="control-label"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address1" class="control-label"></label>
                    <input asp-for="Address1" class="form-control" />
                    <span asp-validation-for="Address1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address2" class="control-label"></label>
                    <input asp-for="Address2" class="form-control" />
                    <span asp-validation-for="Address2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address3" class="control-label"></label>
                    <input asp-for="Address3" class="form-control" />
                    <span asp-validation-for="Address3" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address4" class="control-label"></label>
                    <input asp-for="Address4" class="form-control" />
                    <span asp-validation-for="Address4" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telephone" class="control-label"></label>
                    <input asp-for="Telephone" class="form-control" />
                    <span asp-validation-for="Telephone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PostCode" class="control-label"></label>
                    <input asp-for="PostCode" class="form-control" />
                    <span asp-validation-for="PostCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Save" />
                    <a class="btn btn-danger" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

cafe/Views/Customer/Delete.cshtml
@model cafe.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Customer</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address4)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address4)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

cafe/Views/Customer/Details.cshtml
@model cafe.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h2>Customer Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address4)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address4)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="AddOrEdit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

cafe/Views/Customer/Index.cshtml
@model IEnumerable<cafe.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<h2>Customers List</h2>

<p>
    <a asp-action="AddOrEdit">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                <a asp-action="AddOrEdit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

cafe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cafe</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Customer" asp-action="Index" class="navbar-brand">cafe</a>
            </div>
            
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2022 - cafe</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>